name: Build Docs
on:
  push:
    branches:
      - main
      - develop
  pull_request:
  release:
    types:
      - published

jobs:
  notebooks:
    name: "Build the notebooks for the docs"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
  
      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Build the docs
        run: |
          sphinx-build -b html -j 2 docs/ docs_build/${{ github.ref }}
      
      - name: Save docs artifact
        uses: actions/upload-artifact@v2
        with:
          name: docs
          path: docs_build/*
          retention-days: 1  # should only be needed for a few minutes
      
      # - name: Update doc versions
      #   run: python docs/update_versions.py

      # - name: Deploy docs
      #   uses: JamesIves/github-pages-deploy-action@3.7.1
      #   with:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     BRANCH: docs-deploy
      #     FOLDER: docs_deploy
      #     TARGET_FOLDER: .
      #     PRESERVE: true

      # - name: Print docs link
      #   run: |
      #     echo "Docs available at https://www.adriangb.com/gh-pages-docs/${{ github.ref }}/"
      #     # depends on if you have a custom domain or not
